"""
CliniqAI PDF Report Service
"""
from typing import Dict, Any, List
from datetime import datetime
from fpdf import FPDF


class MedicalReportPDF(FPDF):
    """Custom PDF class for medical reports"""
    
    def header(self):
        self.set_font('Helvetica', 'B', 16)
        self.set_text_color(0, 100, 150)
        self.cell(0, 10, 'CLINIQAI MEDICAL REPORT', border=False, ln=True, align='C')
        self.ln(5)
    
    def section_title(self, title: str):
        self.set_font('Helvetica', 'B', 12)
        self.set_text_color(0, 80, 120)
        self.cell(0, 8, title, border=False, ln=True)
        self.set_text_color(0, 0, 0)
        self.ln(2)
    
    def footer(self):
        self.set_y(-20)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 5, 'Generated by CliniqAI - AI Doctor Second Opinion', border=False, align='C')
        self.cell(0, 5, f'Page {self.page_no()}', border=False, align='R')


def generate_pdf_bytes(
    patient_name: str,
    disease_type: str,
    input_data: Dict[str, Any],
    prediction: Dict[str, Any],
    shap_values: List[Dict[str, Any]],
    clinical_explanation: str
) -> bytes:
    """
    Generate actual PDF report as bytes
    """
    pdf = MedicalReportPDF()
    pdf.add_page()
    
    disease_name = "Diabetes" if disease_type == "diabetes" else "Heart Disease"
    risk_prob = prediction.get("risk_probability", 0) * 100
    risk_category = prediction.get("risk_category", "Unknown")
    ci_low = prediction.get("confidence_interval_low", 0) * 100
    ci_high = prediction.get("confidence_interval_high", 0) * 100
    
    # Report metadata
    pdf.set_font('Helvetica', '', 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 6, f"Report Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True)
    pdf.cell(0, 6, f"Patient Name: {patient_name}", ln=True)
    pdf.cell(0, 6, f"Assessment Type: {disease_name}", ln=True)
    pdf.ln(5)
    
    # Risk Assessment Section
    pdf.section_title("RISK ASSESSMENT")
    pdf.set_font('Helvetica', '', 11)
    pdf.set_text_color(0, 0, 0)
    
    # Risk probability with color coding
    if risk_prob < 30:
        pdf.set_text_color(0, 150, 0)  # Green
    elif risk_prob < 50:
        pdf.set_text_color(200, 150, 0)  # Amber
    elif risk_prob < 70:
        pdf.set_text_color(200, 100, 0)  # Orange
    else:
        pdf.set_text_color(200, 0, 0)  # Red
    
    pdf.set_font('Helvetica', 'B', 14)
    pdf.cell(0, 10, f"Risk Probability: {risk_prob:.1f}%", ln=True)
    pdf.set_text_color(0, 0, 0)
    pdf.set_font('Helvetica', '', 11)
    pdf.cell(0, 8, f"Risk Category: {risk_category}", ln=True)
    pdf.cell(0, 8, f"Confidence Interval: {ci_low:.1f}% - {ci_high:.1f}%", ln=True)
    pdf.ln(5)
    
    # Patient Data Section
    pdf.section_title("PATIENT DATA")
    pdf.set_font('Helvetica', '', 10)
    for key, value in input_data.items():
        formatted_key = key.replace('_', ' ').title()
        pdf.cell(0, 6, f"{formatted_key}: {value}", ln=True)
    pdf.ln(5)
    
    # SHAP Values Section
    pdf.section_title("RISK FACTORS (SHAP VALUES)")
    pdf.set_font('Helvetica', '', 9)
    for i, shap in enumerate(shap_values[:8], 1):
        feature = shap.get("feature", "Unknown")
        value = shap.get("value", 0)
        impact = shap.get("impact", "neutral")
        
        # Color code based on impact
        if impact == "positive":
            pdf.set_text_color(200, 0, 0)
        elif impact == "negative":
            pdf.set_text_color(0, 150, 0)
        else:
            pdf.set_text_color(100, 100, 100)
        
        pdf.cell(0, 5, f"{i}. {feature}: {value:+.4f} ({impact})", ln=True)
    
    pdf.set_text_color(0, 0, 0)
    pdf.ln(5)
    
    # Clinical Interpretation Section
    pdf.section_title("CLINICAL INTERPRETATION")
    pdf.set_font('Helvetica', '', 10)
    pdf.multi_cell(0, 5, clinical_explanation)
    pdf.ln(5)
    
    # Disclaimer Section
    pdf.set_fill_color(250, 250, 250)
    pdf.rect(10, pdf.get_y(), 190, 40, 'F')
    pdf.set_font('Helvetica', 'I', 8)
    pdf.set_text_color(100, 100, 100)
    pdf.multi_cell(0, 4, "DISCLAIMER: This report is generated by an AI-powered risk assessment tool and should NOT be used as the sole basis for medical diagnosis or treatment decisions. Always consult with qualified healthcare professionals for proper medical advice and diagnosis.")
    
    return pdf.output(dest='S').encode('latin-1')


# Keep old function for backwards compatibility
def generate_pdf_report(
    patient_name: str,
    disease_type: str,
    input_data: Dict[str, Any],
    prediction: Dict[str, Any],
    shap_values: List[Dict[str, Any]],
    clinical_explanation: str
) -> str:
    """Generate a text-based medical report (legacy)"""
    pdf_bytes = generate_pdf_bytes(
        patient_name,
        disease_type,
        input_data,
        prediction,
        shap_values,
        clinical_explanation
    )
    return pdf_bytes.decode('latin-1', errors='ignore')
