"""
CliniqAI PDF Report Service
"""
from typing import Dict, Any, List
from datetime import datetime


def generate_pdf_report(
    patient_name: str,
    disease_type: str,
    input_data: Dict[str, Any],
    prediction: Dict[str, Any],
    shap_values: List[Dict[str, Any]],
    clinical_explanation: str
) -> str:
    """
    Generate a text-based medical report
    Returns the report as a formatted string
    """
    
    disease_name = "Diabetes" if disease_type == "diabetes" else "Heart Disease"
    risk_prob = prediction.get("risk_probability", 0) * 100
    risk_category = prediction.get("risk_category", "Unknown")
    ci_low = prediction.get("confidence_interval_low", 0) * 100
    ci_high = prediction.get("confidence_interval_high", 0) * 100
    
    report = f"""
================================================================================
                         CLINIQAI MEDICAL REPORT
================================================================================

Report Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
Patient Name: {patient_name}
Assessment Type: {disease_name}

--------------------------------------------------------------------------------
                           RISK ASSESSMENT
--------------------------------------------------------------------------------

Risk Probability: {risk_prob:.1f}%
Risk Category: {risk_category}
Confidence Interval: {ci_low:.1f}% - {ci_high:.1f}%

--------------------------------------------------------------------------------
                           PATIENT DATA
--------------------------------------------------------------------------------
"""
    
    # Add input data
    for key, value in input_data.items():
        formatted_key = key.replace('_', ' ').title()
        report += f"{formatted_key}: {value}\n"
    
    report += f"""
--------------------------------------------------------------------------------
                        RISK FACTORS (SHAP VALUES)
--------------------------------------------------------------------------------
"""
    
    # Add SHAP values
    for i, shap in enumerate(shap_values[:8], 1):
        feature = shap.get("feature", "Unknown")
        value = shap.get("value", 0)
        impact = shap.get("impact", "neutral")
        report += f"{i}. {feature}: {value:+.4f} ({impact})\n"
    
    report += f"""
--------------------------------------------------------------------------------
                        CLINICAL INTERPRETATION
--------------------------------------------------------------------------------

{clinical_explanation}

--------------------------------------------------------------------------------
                           DISCLAIMER
--------------------------------------------------------------------------------

This report is generated by an AI-powered risk assessment tool and should 
NOT be used as the sole basis for medical diagnosis or treatment decisions.
Always consult with qualified healthcare professionals for proper medical 
advice and diagnosis.

The AI model used for this assessment has been trained on historical data 
and provides risk estimates based on statistical patterns. Individual 
outcomes may vary.

================================================================================
                         END OF REPORT
================================================================================
"""
    
    return report


def generate_pdf_bytes(
    patient_name: str,
    disease_type: str,
    input_data: Dict[str, Any],
    prediction: Dict[str, Any],
    shap_values: List[Dict[str, Any]],
    clinical_explanation: str
) -> bytes:
    """
    Generate PDF report as bytes (for download)
    Currently returns text - can be extended to generate actual PDF
    """
    report = generate_pdf_report(
        patient_name,
        disease_type,
        input_data,
        prediction,
        shap_values,
        clinical_explanation
    )
    return report.encode('utf-8')
